# Generated by Django 2.1.7 on 2019-03-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('KT1', 'Категория1'), ('KT2', 'Категория2'), ('KT3', 'Категория3')], default='KT1', max_length=100)),
            ],
        ),
    ]
