# Generated by Django 2.1.7 on 2019-03-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20190322_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_choice',
            field=models.IntegerField(choices=[(1, 'Credit Card'), ('cat2', 'Student Loans'), ('cat3', 'Taxes'), ('cat4', 'Books'), ('cat5', 'Games'), ('cat6', 'Groceries')], default=1),
        ),
    ]
