# Generated by Django 2.1.7 on 2019-03-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_category_category_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_choice',
            field=models.IntegerField(choices=[(1, 'Credit Card'), (2, 'Student Loans'), (3, 'Taxes'), (4, 'Books'), (5, 'Games'), (6, 'Groceries')], default=1),
        ),
    ]
