# Generated by Django 2.1.7 on 2019-03-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190322_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_choice',
            field=models.CharField(choices=[('cat1', 'cat1'), ('cat2', 'cat2'), ('cat3', 'cat3'), ('cat4', 'cat4'), ('cat5', 'cat5'), ('cat6', 'cat6')], default='cat1', max_length=50),
        ),
    ]
