# Generated by Django 2.1.7 on 2019-03-22 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190322_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_choice',
        ),
    ]
