# Generated by Django 2.1.7 on 2019-03-22 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_remove_category_category_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='year_in_school',
        ),
    ]
