# Generated by Django 2.1.7 on 2019-03-23 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_category_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='polls.Category'),
        ),
        migrations.DeleteModel(
            name='Parent_Category',
        ),
    ]
