# Generated by Django 2.1.7 on 2019-03-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20190323_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specification1',
            field=models.CharField(default='Описание отсутствует', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='specification2',
            field=models.CharField(default='Описание отсутствует', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='specification3',
            field=models.CharField(default='Описание отсутствует', max_length=200),
        ),
    ]
