# Generated by Django 2.1.7 on 2019-03-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20190323_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specification1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification3',
            field=models.TextField(blank=True),
        ),
    ]
