# Generated by Django 2.1.7 on 2019-03-30 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20190323_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf',
            field=models.FileField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
