# Generated by Django 2.1.7 on 2019-04-01 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_auto_20190331_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='specification1',
            new_name='цена',
        ),
    ]
