# Generated by Django 2.1.7 on 2019-04-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_auto_20190401_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='цена',
        ),
        migrations.AddField(
            model_name='product',
            name='specification1',
            field=models.TextField(blank=True, verbose_name='sadasd'),
        ),
    ]
