# Generated by Django 2.1.7 on 2019-04-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_auto_20190401_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='usage',
            field=models.TextField(max_length=200, null=True, verbose_name='Применение'),
        ),
    ]
