# Generated by Django 2.1.7 on 2019-04-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_auto_20190402_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='garant',
            field=models.TextField(blank=True, verbose_name='Гарантия'),
        ),
    ]
